---
title: "Power analysis for independent samples"
author: "Sau-Chin Chen"
date: "2021/11/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
crans <- c("https://cran.csie.ntu.edu.tw/","https://cran.asia/","https://cloud.r-project.org")
if(!require(tidyverse)) {install.packages("tidyverse",repos = crans );library(tidyverse)} 
```

## t檢定

t檢定R函式

`t.test(x, y, alternative, mu, paired)`


- 單一樣本t檢定

```{r sim_norm}
sim_norm <- rnorm(100, 0.5, 1)
t.test(sim_norm, mu = 0)
```

- 獨立樣本t檢定


```{r t-test}
## 建立虛擬資料
a <- rnorm(100, 0.5, 1)
b <- rnorm(100, 0.7, 1)
## 執行t檢定
t_ind <- t.test(a, b, paired = FALSE)
## The `paired` argument defaults to `FALSE`, but it's good practice to always explicitly set it so you are never confused about what type of test you are performing.
## 列印t檢定結果
t_ind
```


- 預覽t檢定函式輸出資訊


```{r names}
names(t_ind)
t_ind$parameter
```

- inline code 示範

a組與b組的獨立樣本t檢定結果: t(`r t_ind$parameter`) = `r t_ind$statistic`, p = `r t_ind$p.value`。


### 獨立樣本t檢定模擬資料

- 建立模擬函式


```{r sim_t_ind}
sim_t_ind <- function(n, m1, sd1, m2, sd2) {
  # simulate v1
  v1 <- rnorm(n, m1, sd1)
  
  #simulate v2
  v2 <- rnorm(n, m2, sd2)
    
  # compare using an independent samples t-test
  t_ind <- t.test(v1, v2, paired = FALSE)
  
  # return the p-value
  return(t_ind$p.value)
}
```

- 測試模擬函式


```{r run-sim_t_ind}
sim_t_ind(100, 0.7, 1, 0.5, 1)
```

### 估計考驗力

- 運用模擬資料估計考驗力

```{r reps}
my_reps <- replicate(1e4, sim_t_ind(100, 0.7, 1, 0.5, 1))

alpha <- 0.05
power <- mean(my_reps < alpha)
power
```

- 模擬結果直方圖

```{r plot-reps}
hist(my_reps)
abline(v=.05,col="green")
```

- 運用公式逼近


```{r power.t.test}
power.t.test(n = 100, 
             delta = 0.2, 
             sd = 1, 
             sig.level = alpha, 
             type = "two.sample")
```


